layout_spectrum: 0.21667328756302595
typography_spectrum: 0.5650894141290337
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.42920004529878497
  lightness: 0.6173852158244699
  saturation: 0.31008920283056796
  rhythmicContrast: 0.07652637152932584
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: GRADUATEiMPACT
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Bible&Culture
    id: c2c0ce79-8b89-4e2b-869e-086acfb3237a
    type: content
  - name: Cross-Current
    id: 170a358f-a99d-4bcc-aeb5-580b553ca890
    type: content
  - name: BiBLENOMICS
    id: f50edf61-b169-4f3a-bd93-f744ceffb7a0
    type: content
favicon: null
title: Ambassadors for Christ for Life
purpose: []
