name: tim
favicon: null
layout_spectrum: 0.7034273070748895
typography_spectrum: 0.5783210920635611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.08865943807177246
  lightness: 0.582871789811179
  saturation: 0.17920523742213845
  rhythmicContrast: 0.12227004184387624
purpose: []
